Added Avocado Prices data
beanumber/moderndive pull request #11
Opened 2022-03-22 19:20 UTC by evejcik

2022-03-22 19:27 UTC, beanumber commented
Working on issue #11

2022-03-23 13:45 UTC, beanumber commented
@evejcik Thanks for starting this PR. Can you add the others mentioned in #4 as collaborators on your fork?

2022-03-24 15:35 UTC, beanumber commented on data-raw/process_data_sets.R
> +usethis::use_data(pennies_resamples, overwrite = TRUE)
`pennies_resamples`???

2022-03-24 15:35 UTC, beanumber commented on R/datasets.R
> +#' \item{Total Bags}{Total Amount of Bags of Avocados}
These variable names have spaces and are not in snake_case. Can you please run `janitor::clean_names()` on them?

2022-03-24 15:56 UTC, tessgold commented on R/datasets.R
> +#' \item{Total Bags}{Total Amount of Bags of Avocados}
added janitor::clean_names to process_data_sets.R and changed names here

2022-03-24 15:56 UTC, tessgold commented on data-raw/process_data_sets.R
> +usethis::use_data(pennies_resamples, overwrite = TRUE)
changed name to avacados

2022-03-24 17:05 UTC, mariumtapal commented on NEWS.md
> +#moderndive 0.5.3.9002
Version number is inconsistent with the one in the DESCRIPTION file. 9002 vs 9003.

2022-03-24 17:05 UTC, mariumtapal commented on R/datasets.R
> +#' @format A data frame of 54 regions over 3 years of weekly results
Please add a blank line before the `@format` line

2022-03-24 17:12 UTC, mariumtapal commented
The `type` variable in the dataset is of type `chr` right now. Because there are only 2 types of avocados, it makes sense to make this variable into a factor.

2022-03-27 16:46 UTC, mariumtapal requested changes

2022-03-27 16:46 UTC, mariumtapal commented on data-raw/process_data_sets.R
> +avocados$type <- as.factor(avocados$type)
Please use `mutate()` to do this

2022-03-27 16:46 UTC, mariumtapal requested changes

2022-03-27 16:46 UTC, mariumtapal commented on data-raw/process_data_sets.R
> +  janitor::clean_names()
You can remove the explicit call to `janitor::` since we load it at the beginning of the script

2022-03-28 02:22 UTC, beanumber requested changes

2022-03-28 02:22 UTC, beanumber commented on NEWS.md
> +#moderndive 0.5.3.9003
Make the next version in the NEWS 0.5.4.

2022-03-28 02:22 UTC, beanumber commented on data-raw/process_data_sets.R
> +usethis::use_data(avocados, overwrite = TRUE)
Why are you changing all of these other data files? Please delete these changes from the PR.

2022-03-30 00:39 UTC, beanumber requested changes

2022-03-30 00:39 UTC, beanumber commented on R/datasets.R
> +#' \item{xlarage_hass_sold}{Amount of Extra Large Haas Avocados Sold}
`x_larage`? Is this a typo?

2022-03-30 00:39 UTC, beanumber commented on NEWS.md
> +# #moderndive 0.5.4
Please remove the extra `#`

2022-03-30 15:35 UTC, beanumber approved these changes
Great work!

2022-03-30 15:36 UTC, merged