Electric Vehicles Pull Request
beanumber/moderndive pull request #12
Opened 2022-03-22 19:21 UTC by q-w-a

We will be adding the Electric Vehicles dataset available [here](https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/NFPQLW) to the moderndive repository.  This dataset contains information from a field experiment on charging electric vehicles at a workplace.

2022-03-23 14:06 UTC, beanumber commented
@q-w-a can you add the others as collaborators to your fork?

2022-03-23 15:01 UTC, q-w-a commented
Yes, I added just added them as collaborators so hopefully that will resolve the permission issue.

2022-03-24 15:33 UTC, q-w-a commented
@rudeboybert 

There is a variable, facilityId, which is defined in [the documentation] (https://github.com/asensio-lab/workplace-charging-experiment) as "a categorical variable indicating the type of facility a station is installed at; manufacturing = 1, office = 2, research and development = 3, other = 4". However, due to this coding, when we read it in R it is a double variable. Would you prefer we leave this variable as is, change it to a factor with levels "manufacturing", "office", etc, or take another approach?

2022-03-24 15:35 UTC, beanumber requested changes

2022-03-24 15:35 UTC, beanumber commented on data-raw/process_data_sets.R
> +electric_vehicle_charging_sessions <- read_csv("https://dataverse.harvard.edu/api/access/datafile/3998649?format=original&gbrecs=true")
This line is too long. Can you use the pipe to split these lines as in the examples above?

2022-03-24 15:35 UTC, beanumber commented on data-raw/process_data_sets.R
> +electric_vehicle_charging_sessions <- read_csv("https://dataverse.harvard.edu/api/access/datafile/3998649?format=original&gbrecs=true")
`electric_vehicle_charging_sessions` is too long of a name. How about `ev_charging`?

2022-03-24 15:41 UTC, rudeboybert commented
Since the categorical variable is not ordinal, please change it to a factor with the levels "manufacturing", "office", etc. In other words, remove the integer labels

2022-03-24 17:19 UTC, mariumtapal requested changes

2022-03-24 17:19 UTC, mariumtapal commented on data-raw/process_data_sets.R
> +  mutate(facilityType = case_when(
The variables in this dataset currently use camel case in their naming. For consistency, please use snake case. `janitor::clean_names()` should do this automatically.

2022-03-24 17:19 UTC, mariumtapal commented on R/datasets.R
> +#'    \item{sessionId}{unique identifier specifying the electric vehicle charging session}
The description of the variables should start with a capital letter

2022-03-24 17:20 UTC, mariumtapal commented
Please delete the old files from the PR: `data/electric_vehicle_charging_sessions.rda` and `man/electric_vehicle_charging_sessions.Rd`.

2022-03-27 16:48 UTC, mariumtapal requested changes

2022-03-27 16:48 UTC, mariumtapal commented on data-raw/process_data_sets.R
> +  janitor::clean_names()
You can remove the explicit call to `janitor::` as it is already loaded at the beginning of the script

2022-03-28 02:25 UTC, beanumber requested changes

2022-03-28 02:25 UTC, beanumber commented on data-raw/process_data_sets.R
> +    facilityType = factor(facilityType,
Try running `styler` on this. I'd put a carriage return after each `(`.

2022-03-29 17:49 UTC, mariumtapal requested changes

2022-03-29 17:49 UTC, mariumtapal commented on data-raw/process_data_sets.R
> +
Please delete this blank line for consistency with other datasets.

2022-03-29 17:49 UTC, mariumtapal commented on data-raw/process_data_sets.R
> +# Original data from: https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/NFPQLW
If you are reading in data from an external URL, you don't need `data-raw/station_data_dataverse.csv`.

2022-03-29 18:10 UTC, mariumtapal requested changes

2022-03-29 18:10 UTC, mariumtapal commented on data-raw/process_data_sets.R
> +# Original data from: https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/NFPQLW
Update: I was told that you do in fact need a csv. Please, instead read in the `csv` from `data-raw` rather than from the URL

2022-03-30 19:45 UTC, beanumber requested changes
Almost there...

2022-03-30 19:45 UTC, beanumber commented on data-raw/process_data_sets.R
> +    facilityType = case_when(
I think you can do this in one fell swoop. Something like:

```
mutate(
  facility_type = factor(
    facilityType, 
    labels = c("manufacturing", "office", "research and development", "other")
  )
)
```

Then you might have to drop the old column afterwards. Can you try this?

2022-03-31 14:17 UTC, beanumber requested changes

2022-03-31 14:17 UTC, beanumber commented on data-raw/process_data_sets.R
> +    facility_type = factor(facilityType,
Can you please put the arguments to `factor()` on their own lines to improve readability?

2022-04-01 13:10 UTC, beanumber approved these changes
Great work!

2022-04-01 13:14 UTC, merged