Added name as contributor
beanumber/moderndive pull request #15
Opened 2022-03-23 16:29 UTC by hartlegr

2022-03-24 17:44 UTC, mariumtapal requested changes

2022-03-24 17:44 UTC, mariumtapal commented on DESCRIPTION
> +Contributors: Grace Hartley <ghartley@smith.edu>, Silas Weden <sweden@smith.edu>
Please look at the format for adding contributors in lines 7 - 12 and update

2022-03-24 17:44 UTC, mariumtapal commented on data-raw/mario-kart-auction.R
> +`mario-kart-auction` <- read_csv("https://www.openintro.org/data/csv/mariokart.csv")
Please use snake case to name the dataset. It should not need backticks. Also pipe the URL to `read_csv`. Look at the processing for other datasets above as an example.

2022-03-24 17:44 UTC, mariumtapal commented on data-raw/mario-kart-auction.R
> +usethis::use_data(mario-kart-auction, overwrite = TRUE)
You need to run this line of code and get a `.rda` file in your PR

2022-03-24 20:37 UTC, hartlegr commented
Are we supposed to have the code that is in `mario_kart_auction.R` in `process_data_sets.R` instead?

2022-03-25 12:02 UTC, beanumber commented
> Are we supposed to have the code that is in `mario_kart_auction.R` in `process_data_sets.R` instead?

Yes.

2022-03-25 12:04 UTC, beanumber requested changes

2022-03-25 12:04 UTC, beanumber commented on DESCRIPTION
> +Contributor: Grace Hartley <ghartley@smith.edu>
Is this a thing? I think you want to add yourself to the `Authors@R` section, similar to how @mariumtapal is listed above.

2022-03-25 12:04 UTC, beanumber commented on DESCRIPTION
> +Contributors: Silas Weden <sweden@smith.edu>
@silasweden you need to move yourself to `Authors@R` as above

2022-03-29 18:07 UTC, mariumtapal requested changes

2022-03-29 18:07 UTC, mariumtapal commented on DESCRIPTION
> +    )
You don't need this parathesis (or line 14). You need a comma at the end of line 13.

2022-03-29 18:07 UTC, mariumtapal commented on DESCRIPTION
> +Contributors:
Please delete line 18.

2022-03-29 18:07 UTC, mariumtapal commented on data-raw/mario_kart_auction.R
> +mario_kart_auction <- "https://www.openintro.org/data/csv/mariokart.csv" %>%
Please read in data from the csv in the `data-raw` folder.

2022-03-29 18:07 UTC, mariumtapal commented on data-raw/mario_kart_auction.R
> +mario_kart_auction <- "https://www.openintro.org/data/csv/mariokart.csv" %>%
The variables in the dataset, `condition`, `ship_sp`, and `stock_photo` should be of type factor, not character.

2022-03-29 18:07 UTC, mariumtapal commented on data-raw/mario_kart_auction.R
> +## code to prepare `mario_kart_auction` dataset goes here
Please put this code in `process_data_sets.R`, not a separate file.

2022-03-29 18:07 UTC, mariumtapal commented on data-raw/mario_kart_auction.R
> +mario_kart_auction <- "https://www.openintro.org/data/csv/mariokart.csv" %>%
Also, documentation is missing.

2022-03-31 14:03 UTC, beanumber requested changes

2022-03-31 14:03 UTC, beanumber commented on NEWS.md
> +# moderndive 0.5.3.9001
*This* version number should be 0.5.4.

2022-03-31 14:03 UTC, beanumber commented on data-raw/process_data_sets.R
> +library(tidyverse)
Please remove the call to `library()`, because `tidyverse` is also loaded at the top of the file.

2022-03-31 14:03 UTC, beanumber commented on data-raw/process_data_sets.R
> +  mutate(cond = as.factor(cond),
Please put the arguments to `mutate()` on their own lines, indented properly.

2022-03-31 14:03 UTC, beanumber commented on data-raw/process_data_sets.R
> +         stock_photo = as.factor(stock_photo))
Please put the closing parenthesis on its own line.

2022-03-31 16:24 UTC, beanumber requested changes

2022-03-31 16:24 UTC, beanumber commented on man/mario_kart_auction.Rd
> +\title{#' Data from Mario Kart Ebay auctions}
You just need to rebuild the documentation and update this file.

2022-03-31 16:41 UTC, hartlegr commented on man/mario_kart_auction.Rd
> +\title{#' Data from Mario Kart Ebay auctions}
Rebuilt the documentation to update this file, but didn't change any content of the documentation beyond title. Is that what you meant?

2022-04-01 12:45 UTC, beanumber approved these changes
Great job!

2022-04-01 12:48 UTC, merged