Saratoga nyc housing prices
beanumber/moderndive pull request #21
Opened 2022-03-24 15:42 UTC by hongtonglin

2022-03-25 17:01 UTC, beanumber requested changes

2022-03-25 17:01 UTC, beanumber commented on DESCRIPTION
> +Description: 🍒 Datasets and wrapper functions for tidyverse-friendly introductory linear regression, used in "Statistical Inference via Data Science: A ModernDive into R and the Tidyverse" available
Did you mean to add a cherry emoji here? I don't think this will fly!

2022-03-25 17:01 UTC, beanumber commented on R/st_nyc_housing_prices.R
> +st_nyc_housing_prices <- read.csv("/Users/cynthialin/Downloads/saratoga_ny_home_prices (1).csv")
Saratoga is not part of New York City. I'd suggest `saratoga_houses` as a name.

2022-03-25 17:01 UTC, beanumber commented on R/st_nyc_housing_prices.R
> +usethis::use_data(st_nyc_housing_prices, overwrite=TRUE)
Please put spaces around `=`

2022-03-25 17:01 UTC, beanumber commented on R/st_nyc_housing_prices.R
> +st_nyc_housing_prices <- read.csv("/Users/cynthialin/Downloads/saratoga_ny_home_prices (1).csv")
Please pipe the URL into `read_csv()`

2022-03-30 17:07 UTC, beanumber commented
@alejanmg @egordonhalpern are you seeing these messages?

2022-04-01 17:49 UTC, beanumber commented
We still need to add to the NEWS.md, and write the documentation for the data set.

2022-04-01 18:15 UTC, beanumber requested changes

2022-04-01 18:15 UTC, beanumber commented on DESCRIPTION
> +Description: contributers: Hongtong, Alejandra, Elina
No. Please restore the previous Description of the package.

2022-04-01 18:15 UTC, beanumber commented on R/st_nyc_housing_prices.R
> +saratoga_houses <- read.csv("https://wjhopper.github.io/SDS-201/data/saratoga_ny_home_prices.csv")
You want to put this code at the bottom of the `data-raw/process_data_sets.R` file. 

Please also put the URL on the first line and pipe the result into `read_csv()`.

2022-04-01 22:30 UTC, closed without merging

2022-04-01 22:33 UTC, hongtonglin commented
i renamed my branch to sartaoga-houses. Do i need to make a new pull request??